<?php

namespace App\Exports\MME_Export\STI;

use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\WithMapping;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithChunkReading;
use Illuminate\Support\Collection;
use Maatwebsite\Excel\Concerns\WithColumnWidths;
use Maatwebsite\Excel\Concerns\WithColumnFormatting;

class STIExport implements FromCollection, WithMapping, WithHeadings, WithChunkReading, WithColumnFormatting, WithColumnWidths
{
	private $sti_records, $testName;
	public function __construct($sti_records, $testName)
	{
		$this->sti_records = $sti_records;
		$this->testName = $testName;
	}

	// public function view(): View
	// {
	// 	return view("MME.Export.STI.STI_" . $this->testName, [
	// 		"sti_records" => $this->sti_records,
	// 	]);
	// }
	public function collection()
	{
		return $this->sti_records;
	}
	public function map($row): array
	{
		if ($this->testName == "Male") {
			return [
				$row->getConnectionName(),
				$row["Clinic Code"],
				$row["CID"],
				$row["FuchiaID"],
				$row["Gender"],
				$row['Reg year'],
				$row['Register Agey'],
				$row['Register Agem'],
				$row['Current Agey'],
				$row['Current Agem'],
				$row["Visit_date"],

				$row["last_vis_within"],
				$row["about_clinic"],
				$row["demo_remarks"],
				$row["visit_type"],
				$row["visit_time"],
				$row["followup_visit"],
				$row["episode"],
				$row["Reason for Visit"],
				$row["Main Risk"],
				$row["Sub Risk"],
				$row["urethral_disc"],
				$row["urethral_disc_hl"],
				$row["dysuria"],
				$row["dysuria_hl"],
				$row["genital_prut"],
				$row["genital_prut_hl"],
				$row["genital_pain"],
				$row["genital_pain_hl"],
				$row["genital_ulcer"],
				$row["genital_ulcer_hl"],
				$row["pain"],
				$row["ulcer"],
				$row["prodromal_itch"],
				$row["vesicles"],
				$row["recurrent"],
				$row["last_episode"],
				$row["suspects_herpes"],
				$row["ing_lymph_node"],
				$row["ing_lymph_node_hl"],
				$row["unilateal"],
				$row["leg_ulcer"],
				$row["scrotal_swelling"],
				$row["scrotal_swelling_hl"],
				$row["td_ntd"],
				$row["gen_wart"],
				$row["gen_wart_hl"],
				$row["physical_exam"],
				$row["urinated_wit_1h"],
				$row["discharge"],
				$row["discharge_milk"],
				$row["colour"],
				$row["erythema"],
				$row["blisters"],
				$row["gen_ulcer"],
				$row["esti_size"],
				$row["sing_multi"],
				$row["pain_full_less"],
				$row["herpes_suspect"],
				$row["inguinal_bubo"],
				$row["fluctant"],
				$row["tendr_ntender"],
				$row["oth_leg_inf"],
				$row["phy_genital_wart"],
				$row["crab_lice"],
				$row["scabies"],
				$row["gscrotal_swelling"],
				$row["estimated_siz"],
				$row["unilateal_bilateral"],
				$row["gtender_ntender"],
				$row["erythem"],
				$row["des_size"],
				$row["tbl_treat_diagnosis_first_visit"],
				$row["epi_discharge"],
				$row["unprot_sex_new_part"],
				$row["genital_signs"],
				$row["presumptive_diag"],
				$row["pri_syphillis"],
				$row["sec_syphillis"],
				$row["chancroid"],
				$row["gen_herpes"],
				$row["gen_scabies"],
				$row["gud_other"],
				$row["other(please specify)"],
				$row["Gonorhoea"],
				$row["non_gono_urethritis"],
				$row["non_gono_procti"],
				$row["trichomonas"],
				$row["genital_candidiosis"],
				$row["beterial_vaginosis"],
				$row["congenial_syphillis"],
				$row["latent_syphillis"],
				$row["molluscum_contag"],
				$row["bubos"],
				$row["othstd_genital_warts"],
				$row["ostd_other"],
				$row["tre_azythro"],
				$row["tre_cefixim"],
				$row["tre_ciprofloxacin"],
				$row["tre_tinidazole"],
				$row["tre_fluconazole"],
				$row["tre_doxycycline"],
				$row["tre_ceftriaxone"],
				$row["tre_benz_pen"],
				$row["no_treat"],
				$row["al_Penicillin"],
				$row["al_sulfa"],
				$row["part_treat"],
				$row["condom_giv"],
				$row["tre_remarks"],
				$row["followup"],
				$row["clinician_name"],
			];
		} else {
			return [
				$row->getConnectionName(),
				$row["Clinic Code"],
				$row["CID"],
				$row["FuchiaID"],
				$row["Gender"],
				$row["Reg year"],
				$row["Register Agey"],
				$row["Register Agem"],
				$row["Current Agey"],
				$row["Current Agem"],
				$row["Visit_date"],
				$row["first_visit"],



				$row["last_vis_within"],
				$row["vtype"],
				$row["about_clinic"],
				$row["demo_remarks"],
				$row["episode"],
				$row["rea_for_visit"],
				$row["Main Risk"],
				$row["Sub Risk"],
				$row["abn_vaginal_disc"],
				$row["abn_vaginal_disc_long"],
				$row["linked_menstru"],
				$row["amount"],
				$row["colour"],
				$row["colour_oth"],
				$row["abn_veginal_odour"],
				$row["l_abn_pain"],
				$row["l_abon_pain_hl"],
				$row["fever"],
				$row["rec_terminate_preg"],
				$row["dyspareunia"],
				$row["oth_GI_sympt"],
				$row["dysuria"],
				$row["dysuria_hl"],
				$row["gen_prutitus"],
				$row["gen_prutitus_hl"],
				$row["gen_burn_pain"],
				$row["gen_burn_pain_hl"],
				$row["gen_ulcer"],
				$row["gen_ulcer_hl"],
				$row["pain"],
				$row["ulcer"],
				$row["prodromal_itch"],
				$row["vesicles"],
				$row["recurrent"],
				$row["recurrent_last_episode"],
				$row["patient_suspects_herpes"],
				$row["inguinal_ln"],
				$row["inguinal_ln_hl"],
				$row["unilateal_Bilateral"],
				$row["leg_ulcer_oth_inf"],
				$row["genital_warts"],
				$row["genital_warts_hl"],
				$row["phy_exam_done"],
				$row["washed_inside"],
				$row["vulvar_erythema"],
				$row["vulvar_odema"],
				$row["vaginal_discharge"],
				$row["vag_dis_amount"],
				$row["homogeneous"],
				$row["homogeneous_col"],
				$row["smell_without_KOH"],
				$row["vaginal_wall_injury"],
				$row["adnexal_tenderness"],
				$row["adnexal_enlargement"],
				$row["genital_blisters"],
				$row["genital_blisters_Location"],
				$row["gential_ulcer"],
				$row["gential_ulcerl"],
				$row["gent_ulcer_sm"],
				$row["gential_ulcer_pain"],
				$row["susp_herpes"],
				$row["inguinal_bubo"],
				$row["fluctuant"],
				$row["fluctuant_tender"],
				$row["oth_leg_infection"],
				$row["genital_wart"],
				$row["crab_lice"],
				$row["scablices"],
				$row["KOH_smell_test"],
				$row["pH_vagina"],
				$row["des_size"],
				$row["prev_STI"],
				$row["patient_genital_ulcer"],
				$row["patient_compl_low_abd"],
				$row["new_pat_past_3mont"],
				$row["part_compl_gential_sym"],
				$row["sworker"],
				$row["rg_score"],
				$row["risk"],
				$row["risk_cal_remark"],
				$row["abn_yellow_disc"],
				$row["dysuria_risk_ass"],
				$row["low_abd_pain"],
				$row["pain_dur_sexual"],
				$row["unp_sex_new_clients"],
				$row["partner_ulcer"],
				$row["presumptive_diag"],
				$row["pri_syphillis"],
				$row["sec_syphillis"],
				$row["chancroid"],
				$row["gen_herpes"],
				$row["gen_scabies"],
				$row["gud_other"],
				$row["other(please specify)"],
				$row["Gonorhoea"],
				$row["non_gono_urethritis"],
				$row["non_gono_cervities"],
				$row["trichomonas"],
				$row["genital_candidiosis"],
				$row["beterial_vaginosis"],
				$row["congenial_syphillis"],
				$row["latent_syphillis"],
				$row["latent_syphillis_preg"],
				$row["molluscum_contag"],
				$row["bubos"],
				$row["othstd_genital_warts"],
				$row["ostd_other"],
				$row["tre_azythro"],
				$row["tre_cefixim"],
				$row["tre_ciprofloxacin"],
				$row["tre_tinidazole"],
				$row["tre_fluconazole"],
				$row["tre_doxycycline"],
				$row["tre_ceftriaxone"],
				$row["tre_benz_pen"],
				$row[""], //insert tre_other to no_treatment
				$row["clotrimazole_vaginal_tab"],
				$row["tre_Other"], //<!-- no_treatment -->
				$row["al_Penicillin"],
				$row["al_sulfa"],
				$row["part_treat"],
				$row["condom_giv"],
				$row["tre_remarks"],
				$row["followup"],
				$row["clinician"],

			];
		}
	}

	public function headings(): array
	{
		if ($this->testName == "Male") {
			return [
				'Database',
				'Clinic Code',
				'General ID',
				'Fuchia ID',
				'Sex',
				'Reg Year',
				'Register Age',
				'Register Age(Month)',
				'Current Age',
				'Current Age(Month)',
				'Visit date',
				'last_vis_within',
				'about_clinic',
				'demo_remarks',
				'visit_type',
				'visit_time',
				'followup_visit',
				'episode',
				'Reason for Visit',
				'Main Risk',
				'Sub Risk',
				'urethral_disc',
				'urethral_disc_hl',
				'dysuria',
				'dysuria_hl',
				'genital_prut',
				'genital_prut_hl',
				'genital_pain',
				'genital_pain_hl',
				'genital_ulcer',
				'genital_ulcer_hl',
				'pain',
				'ulcer',
				'prodromal_itch',
				'vesicles',
				'recurrent',
				'last_episode',
				'suspects_herpes',
				'ing_lymph_node',
				'ing_lymph_node_hl',
				'unilateal',
				'leg_ulcer',
				'scrotal_swelling',
				'scrotal_swelling_hl',
				'td_ntd',
				'gen_wart',
				'gen_wart_hl',
				'physical_exam',
				'urinated_wit_1h',
				'discharge',
				'discharge_milk',
				'colour',
				'erythema',
				'blisters',
				'gen_ulcer',
				'esti_size',
				'sing_multi',
				'pain_full_less',
				'herpes_suspect',
				'inguinal_bubo',
				'fluctant',
				'tendr_ntender',
				'oth_leg_inf',
				'phy_genital_wart',
				'crab_lice',
				'scabies',
				'gscrotal_swelling',
				'estimated_siz',
				'unilateal_bilateral',
				'gtender_ntender',
				'erythem',
				'des_size',
				'tbl_treat_diagnosis_first_visit',
				'epi_discharge',
				'unprot_sex_new_part',
				'genital_signs',
				'presumptive_diag',
				'pri_syphillis',
				'sec_syphillis',
				'chancroid',
				'gen_herpes',
				'gen_scabies',
				'gud_other',
				'other(please specify)',
				'Gonorhoea',
				'non_gono_urethritis',
				'non_gono_procti',
				'trichomonas',
				'genital_candidiosis',
				'beterial_vaginosis',
				'congenial_syphillis',
				'latent_syphillis',
				'molluscum_contag',
				'bubos',
				'othstd_genital_warts',
				'ostd_other',
				'tre_azythro',
				'tre_cefixim',
				'tre_ciprofloxacin',
				'tre_tinidazole',
				'tre_fluconazole',
				'tre_doxycycline',
				'tre_ceftriaxone',
				'tre_benz_pen',
				'no_treat',
				'al_Penicillin',
				'al_sulfa',
				'part_treat',
				'condom_giv',
				'tre_remarks',
				'followup',
				'clinician_name',
			];
		} else {
			return [
				'Database',
				"Clinic Code",
				"General ID",
				"Fuchia ID",
				"Sex",
				"Reg Year",
				"Register Age",
				"Register Age(Month)",
				"Current Age",
				"Current Age(Month)",
				"Visit date",
				"first visit",

				"last_vis_within",
				"visit_type",
				"about_clinic",
				"demo_remarks",


				"episode",
				"Reason for Visit",
				"Main Risk",
				"Sub Risk",

				"abn_vaginal_disc",
				"abn_vaginal_disc_long",
				"linked_menstru",
				"amount",
				"colour",
				"colour_oth",
				"abn_veginal_odour",
				"l_abn_pain",
				"l_abon_pain_hl",
				"fever",
				"rec_terminate_preg",
				"dyspareunia",
				"oth_GI_sympt",
				"dysuria",
				"dysuria_hl",
				"gen_prutitus",
				"gen_prutitus_hl",
				"gen_burn_pain",
				"gen_burn_pain_hl",
				"gen_ulcer",
				"gen_ulcer_hl",
				"pain",
				"ulcer",
				"prodromal_itch",
				"vesicles",
				"recurrent",
				"recurrent_last_episode",
				"patient_suspects_herpes",
				"inguinal_ln",
				"inguinal_ln_hl",
				"unilateal_Bilateral",
				"leg_ulcer_oth_inf",
				"genital_warts",
				"genital_warts_hl",
				"phy_exam_done",
				"washed_inside",
				"vulvar_erythema",
				"vulvar_odema",
				"vaginal_discharge",
				"vag_dis_amount",
				"homogeneous",
				"homogeneous_col",
				"smell_without_KOH",
				"vaginal_wall_injury",
				"adnexal_tenderness",
				"adnexal_enlargement",
				"genital_blisters",
				"genital_blisters_Location",
				"gential_ulcer",
				"gential_ulcerl",
				"gent_ulcer_sm",
				"gential_ulcer_pain",
				"susp_herpes",
				"inguinal_bubo",
				"fluctuant",
				"fluctuant_tender",
				"oth_leg_infection",
				"genital_wart",
				"crab_lice",
				"scablices",
				"KOH_smell_test",
				"pH_vagina",
				"des_size",
				"prev_STI",
				"patient_genital_ulcer",
				"patient_compl_low_abd",
				"new_pat_past_3mont",
				"part_compl_gential_sym",
				"sworker",
				"rg_score",
				"risk",
				"risk_cal_remark",
				"abn_yellow_disc",
				"dysuria_risk_ass",
				"low_abd_pain",
				"pain_dur_sexual",
				"unp_sex_new_clients",
				"partner_ulcer",
				"presumptive_diag",
				"pri_syphillis",
				"sec_syphillis",
				"chancroid",
				"gen_herpes",
				"gen_scabies",
				"gud_other",
				"other(please specify)",
				"Gonorhoea",
				"non_gono_urethritis",
				"non_gono_cervities",
				"trichomonas",
				"genital_candidiosis",
				"beterial_vaginosis",
				"congenial_syphillis",
				"latent_syphillis",
				"latent_syphillis_preg",
				"molluscum_contag",
				"bubos",
				"othstd_genital_warts",
				"ostd_other",
				"tre_azythro",
				"tre_cefixim",
				"tre_ciprofloxacin",
				"tre_tinidazole",
				"tre_fluconazole",
				"tre_doxycycline",
				"tre_ceftriaxone",
				"tre_benz_pen",
				"tre_Other",
				"clotrimazole_vaginal_tab",
				"no_treatment",
				"al_Penicillin",
				"al_sulfa",
				"part_treat",
				"condom_giv",
				"tre_remarks",
				"followup",
				"clinician",
			];
		}
	}
	public function chunkSize(): int
	{
		return 5000; // Process 1,000 rows at a time
	}
	public function columnWidths(): array
	{
		return array_fill_keys(array_merge(range('A', 'Z'), range('AA', 'AZ')), 15);
	}
	public function columnFormats(): array
	{
		return [
			"K" => "d-m-YYYY",
		];
	}
}
