<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class HtyANcdFollowup extends Model
{
    use HasFactory;
    protected $fillable = [
      'pid'                         ,
      'pt_fuchiaid'                 ,
      'Visit_date'                  ,
      'visit_type'                  ,
      'visitdt'                     ,
      'fu_fuchiaid'                ,
      'NCD_Diagnosis'               ,
      'weight'                      ,
      'height'                      ,
      'bmi'                         ,
      'curage'                      ,
      'stage_of_hypertension'       ,
      'rbs_result'                  ,
      'fbs_result'                  ,
      'HBA1C'                       ,
      'HbA1C_Unit'                  ,
      'fsystBP'                     ,
      'fdiasBP'                     ,
      'urinalysis'                  ,
      'creatinine'                  ,
      'Serum_creatinine_unit'       ,
      'invistigations'              ,
      'rbs_next_appt'               ,
      'crcl'                        ,
      'fbs_next_appt'               ,
      'hba1c_next_appt'             ,
      'urine_acr'                   ,
      'bp_next_appt'                ,
      'total_cholesterol'           ,
      'Total_Cholesterol_Unit'      ,
      'uri_next_appt'               ,
      'triglyceride'                ,
      'Triglyceride_unit'           ,
      'hdl'                         ,
      'HDL_unit'                    ,
      'ldl'                         ,
      'LDL unit'                    ,
      'CVD risk'                    ,
      'Statin_Y/N'                  ,
      'alt'                         ,
      'Urine_done/not_done'         ,
      'protein_res'                 ,
      'glucose_res'                 ,
      'urine_oth'                   ,
      'oth_inv1'                    ,
      'oth_inv1_res'                ,
      'oth_inv2'                    ,
      'oth_inv2_res'                ,
      'oth_inv3'                    ,
      'oth_inv3_res'                ,
      'oth_inv4'                    ,
      'oth_inv4_res'                ,
      'oth_inv5'                    ,
      'oth_inv5_res'                ,
      'oth_inv6'                    ,
      'oth_inv6_res'                ,
      'Lifestyle_advice'            ,
      'Medication_changed'          ,
      'Patient_adherence_to_medication',
      'Amlodipine_dose'             ,
      'Amlodipine_frequency'        ,
      'famlodipine_dur'             ,
      'Enalapril_dose'              ,
      'Enalapril_frequency'         ,
      'fenalapril_dur'              ,
      'Atorvastain_dose'            ,
      'Atorvastain_frequency'       ,
      'fatorvastain_dur'            ,
      'Hydrochlorothiazide dose'    ,
      'Hydrochlorothiazide frequency',
      'fhydrochlorothiazide_dur'    ,
      'Aspirin_dose'                ,
      'Aspirin_frequency'           ,
      'faspirin_dur'                ,
      'Metformin_500_dose'          ,
      'Metformin_500_frequency'     ,
      'fmetformin500_dur'           ,
      'Metformin_1000_dose'         ,
      'Metformin_1000_frequency'    ,
      'fmetformin1000_dur'          ,
      'Gliclazide_500_dose'         ,
      'Gliclazide_500_frequency'    ,
      'fgliclazide500_dur'          ,
      'Gliclazide_1000_dose'        ,
      'Gliclazide_1000_frequency'   ,
      'fgliclazide1000_dur'         ,
      'Symptom_hypoglycemia'        ,
      'oth_complains'               ,
      'Followup_Other_Medication'   ,
      'foth_med_spec'               ,
      'Referral_to_secondary_care'  ,
      'ref_res'                     ,
      'Hypertension_control'        ,
      'Diabetes_control'            ,
      'Next_appointment_date'       ,
      'Doctor_Name'                  ];
}
