<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class ncd_pt_register extends Model
{
    use HasFactory;
    protected $fillable = [
        'pid'             ,
        'Fuchsia_ID'     ,
        'Age'             ,
        'Agey'           ,
        'Reg_Date'        ,
        'Area_Division'  ,
        'Township'       ,
        'Height'          ,
        'Weight'          ,
        'Gender'          ,
        '1stBP_Up'        ,
        '1stBP_Low'       ,
        '1stBP_date'      ,
        '2ndBP_Up'        ,
        '2ndBP_Low'       ,
        '2ndBP_date'     ,
        '3rdBP_Up' ,
        '3rdBP_Low' ,
        '3rdBP_date'     ,
        'Hypertension'   ,
        'Hyper_Di_date'  ,
        'Diabetes'       ,
        'Dia_Dig_date'   ,
        'Stage_of_Hyper'  ,
        '1st_RBS'         ,
        '1st_RBS_date'   ,
        '2nd_RBS'        ,
        '2nd_RBS_date'    ,
        'Clinical_Symptoms'      ,
        'Clinical_Symptoms_Text' ,
        'Smoking_Status'         ,
        'Amlodipine_dose'       ,
        'Amlodipine_Freq'         ,
        'Amlodipine_due' ,
        'Enalapril_dose' ,
        'Enalapril_Freq'  ,
        'Enalapril_due'   ,
        'Atorvastain_dose' ,
        'Atorvastain_Freq' ,
        'Atorvastain_due' ,
        'Hydrochlorothiazide_dose' ,
        'Hydrochlorothiazide_Freq'  ,
        'Hydrochlorothiazide_due'   ,
        'Aspirin_dose'   ,
        'Aspirin_Freq'   ,
        'Aspirin_due'    ,
        'Metformin_dose' ,
        'Metformin_Freq'  ,
        'Metformin_due'  ,
        'Gliclazide_dose' ,
        'Gliclazide_Freq' ,
        'Gliclazide_due'  ,
        'otherNCDMed',
        'othr_ncd_text',
        'cur_med1'             ,
        'cur_med1_dose'         ,
        'cur_med1_freq',
        'cur_med1_due' ,
        'cur_med2' ,
        'cur_med2_dose',
        'cur_med2_freq' ,
        'cur_med2_due'  ,
        'cur_med3'   ,
        'cur_med3_dose',
        'cur_med3_freq' ,
        'cur_med3_due' ,
        'cur_med4' ,
        'cur_med4_dose',
        'cur_med4_freq' ,
        'cur_med4_due'  ,
        'cur_med5' ,
        'cur_med5_dose' ,
        'cur_med5_freq' ,
        'cur_med5_due'  ,
        'cur_med6'  ,
        'cur_med6_dose',
        'cur_med6_freq',
        'cur_med6_due' ,
        'Dia_foot' ,
        'Neuropathy',
        'Atril_Fib' ,
        'Hyperlipidemia' ,
        'CKD'  ,
        'Change_in_Vision',
        'Gestational_Diabetes' ,
        'CVD' ,
        'Chronic_Lung_Disease' ,
        'Recur_infection' ,
        'Recur_infection_text',
        'Family_Hyper' ,
        'Family_Diabetes',
    ];
}
