<?php

namespace App\Imports;
//use App\Models\User;
use App\Models\Stifemale;
use Illuminate\Support\Facades\Hash;
use Maatwebsite\Excel\Concerns\ToModel;
use Maatwebsite\Excel\Concerns\WithHeadingRow;

class StiFemaleImport implements ToModel
{
    /**
    * @param array $row
    *
    * @return \Illuminate\Database\Eloquent\Model|null
    */
    public function model(array $row)
    {
        return new Stifemale([
          'gender'=>                    $row[0],
          'clinic'=>                    $row[1],
          'CID'=>                       $row[2],
          'first_visit'=>               $row[3],
          'last_vis_within'=>           $row[4],
          'vtype'=>                     $row[5],
          'age'=>                       $row[6],
          'about_clinic'=>              $row[7],
          'demo_remarks'=>              $row[8],
          'Visit date'=>                $row[9],
          'Expr1'=>                     $row[10],
          'episode'=>                   $row[11],
          'rea_for_visit'=>             $row[12],
          'risk_factor'=>               $row[13],
          'abn_vaginal_disc'=>          $row[14],
          'abn_vaginal_disc_long'=>     $row[15],
          'linked_menstru'=>            $row[16],
          'amount'=>                    $row[17],
          'colour'=>                    $row[18],
          'colour_oth'=>                $row[19],
          'abn_veginal_odour'=>         $row[20],
          'l_abn_pain'=>                $row[21],
          'l_abon_pain_hl'=>            $row[22],
          'fever'=>                     $row[23],
          'rec_terminate_preg'=>        $row[24],
          'dyspareunia'=>               $row[25],
          'oth_GI_sympt'=>              $row[26],
          'dysuria'=>                   $row[27],
          'dysuria_hl'=>                $row[28],
          'gen_prutitus'=>              $row[29],
          'gen_prutitus_hl'=>           $row[30],
          'gen_burn_pain'=>             $row[31],
          'gen_burn_pain_hl'=>          $row[31],
          'gen_ulcer'=>                 $row[33],
          'gen_ulcer_hl'=>              $row[34],
          'pain'=>                      $row[35],
          'ulcer'=>                     $row[36],
          'prodromal_itch'=>            $row[37],
          'vesicles'=>                  $row[38],
          'recurrent'=>                 $row[39],
          'recurrent_last_episode'=>    $row[40],
          'patient_suspects_herpes'=>   $row[41],
          'inguinal_ln'=>               $row[42],
          'inguinal_ln_hl'=>            $row[43],
          'unilateal_Bilateral'=>       $row[44],
          'leg_ulcer_oth_inf'=>         $row[45],
          'genital_warts'=>             $row[46],
          'genital_warts_hl'=>          $row[47],
          'phy_exam_done'=>             $row[48],
          'washed_inside'=>             $row[49],
          'vulvar_erythema'=>           $row[50],
          'vulvar_odema'=>              $row[51],
          'vaginal_discharge'=>         $row[52],
          'vag_dis_amount'=>            $row[53],
          'homogeneous'=>               $row[54],
          'homogeneous_col'=>           $row[55],
          'smell_without_KOH'=>         $row[56],
          'vaginal_wall_injury'=>       $row[57],
          'adnexal_tenderness'=>        $row[58],
          'adnexal_enlargement'=>       $row[59],
          'genital_blisters'=>          $row[60],
          'genital_blisters_Location'=> $row[61],
          'gential_ulcer'=>             $row[62],
          'gential_ulcerl'=>            $row[63],
          'gent_ulcer_sm'=>             $row[64],
          'gential_ulcer_pain'=>        $row[65],
          'susp_herpes'=>               $row[66],
          'inguinal_bub'=>              $row[67],
          'fluctuant'=>                 $row[68],
          'fluctuant_tender'=>          $row[69],
          'oth_leg_infection'=>         $row[70],
          'genital_wart'=>              $row[71],
          'crab_lice'=>                 $row[72],
          'scablices'=>                 $row[73],
          'KOH_smell_test'=>            $row[74],
          'pH_vagina'=>                 $row[75],
          'des_size'=>                  $row[76],
          'prev_STI'=>                  $row[77],
          'patient_genital_ulcer'=>     $row[78],
          'patient_compl_low_abd'=>     $row[79],
          'new_pat_past_3mont'=>        $row[80],
          'part_compl_gential_sym'=>    $row[81],
          'sworker'=>                   $row[82],
          'rg_score'=>                  $row[83],
          'risk'=>                      $row[84],
          'risk_cal_remark'=>           $row[85],
          'abn_yellow_disc'=>           $row[86],
          'dysuria_risk_ass'=>          $row[87],
          'low_abd_pain'=>              $row[88],
          'pain_dur_sexual'=>           $row[89],
          'unp_sex_new_clients'=>       $row[90],
          'partner_ulcer'=>             $row[91],
          'presumptive_diag'=>          $row[92],
          'pri_syphillis'=>             $row[93],
          'sec_syphillis'=>             $row[94],
          'chancroid'=>                 $row[95],
          'gen_herpes'=>                $row[96],
          'gen_scabies'=>               $row[97],
          'gud_other'=>                 $row[98],
          'other_plz_specify'=>         $row[99],
          'Gonorhoea'=>                 $row[100],
          'non_gono_urethritis'=>       $row[101],
          'non_gono_cervities'=>        $row[102],
          'trichomonas'=>               $row[103],
          'genital_candidiosis'=>       $row[104],
          'beterial_vaginosis'=>        $row[105],
          'congenial_syphillis'=>       $row[106],
          'latent_syphillis'=>          $row[107],
          'latent_syphillis_preg'=>     $row[108],
          'molluscum_contag'=>          $row[109],
          'bubos'=>                     $row[110],
          'othstd_genital_warts'=>      $row[111],
          'ostd_other'=>                $row[112],
          'tre_azythro'=>               $row[113],
          'tre_cefixim'=>               $row[114],
          'tre_ciprofloxacin'=>         $row[115],
          'tre_tinidazole'=>            $row[116],
          'tre_fluconazole'=>           $row[117],
          'tre_doxycycline'=>           $row[118],
          'tre_ceftriaxone'=>           $row[119],
          'tre_benz_pen'=>              $row[120],
          'tre_Other'=>                 $row[121],
          'clotrimazole_vaginal_tab'=>  $row[122],
          'no_treatment'=>              $row[123],
          'al_Penicillin'=>             $row[124],
          'al_sulfa'=>                  $row[125],
          'part_treat'=>                $row[126],
          'condom_giv'=>                $row[127],
          'tre_remarks'=>               $row[128],
          'followup'=>                  $row[129],
          'clinician'=>                 $row[130],

        ]);
    }
}
